/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root';
import { Route as AuthRouteImport } from './pages/_auth';
import { Route as AppRouteImport } from './pages/_app';
import { Route as R404RouteImport } from './pages/404';
import { Route as AuthLoginRouteImport } from './pages/_auth/login';
import { Route as AppSettingsRouteImport } from './pages/_app/settings';
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard';

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/404': typeof R404Route;
  '/': typeof AuthRouteWithChildren;
  '/dashboard': typeof AppDashboardRoute;
  '/settings': typeof AppSettingsRoute;
  '/login': typeof AuthLoginRoute;
}
export interface FileRoutesByTo {
  '/404': typeof R404Route;
  '/': typeof AuthRouteWithChildren;
  '/dashboard': typeof AppDashboardRoute;
  '/settings': typeof AppSettingsRoute;
  '/login': typeof AuthLoginRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/404': typeof R404Route;
  '/_app': typeof AppRouteWithChildren;
  '/_auth': typeof AuthRouteWithChildren;
  '/_app/dashboard': typeof AppDashboardRoute;
  '/_app/settings': typeof AppSettingsRoute;
  '/_auth/login': typeof AuthLoginRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/404' | '/' | '/dashboard' | '/settings' | '/login';
  fileRoutesByTo: FileRoutesByTo;
  to: '/404' | '/' | '/dashboard' | '/settings' | '/login';
  id: '__root__' | '/404' | '/_app' | '/_auth' | '/_app/dashboard' | '/_app/settings' | '/_auth/login';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  R404Route: typeof R404Route;
  AppRoute: typeof AppRouteWithChildren;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/404': {
      id: '/404';
      path: '/404';
      fullPath: '/404';
      preLoaderRoute: typeof R404RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_app/settings': {
      id: '/_app/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/dashboard': {
      id: '/_app/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
